name: Deploy to Server

on:
  push:
    branches:
      - push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: SCP files to server
        uses: appleboy/scp-action@v0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./build/
          target: ${{ secrets.DEPLOY_PATH }}
